"""Render a ScanRun (+ optional AI Analysis) into a Markdown report."""
from __future__ import annotations

from datetime import datetime

from ..ai.base import Analysis
from ..model import ScanRun, Severity

_BADGE = {
    Severity.CRITICAL: "🔴 CRITICAL",
    Severity.HIGH: "🟠 HIGH",
    Severity.MEDIUM: "🟡 MEDIUM",
    Severity.LOW: "🟢 LOW",
    Severity.INFO: "⚪ INFO",
}


def render(scan: ScanRun, analysis: Analysis | None) -> str:
    out: list[str] = []
    out.append(f"# Security Assessment — {scan.target}\n")
    out.append("> ⚠️ **Authorized testing only.** This report was generated against a target the "
               "operator asserted they own or are permitted to assess.\n")
    out.append(f"- **Target:** `{scan.target}`")
    out.append(f"- **Started:** {scan.started_at.isoformat(timespec='seconds')}")
    if scan.finished_at:
        out.append(f"- **Finished:** {scan.finished_at.isoformat(timespec='seconds')}")
    if scan.tool_versions:
        tv = ", ".join(f"{k} {v}" for k, v in scan.tool_versions.items())
        out.append(f"- **Tools:** {tv}")
    out.append("")

    # Severity matrix from AI findings (fallback to rule flags)
    findings = analysis.findings if analysis else []
    counts = {s: 0 for s in Severity}
    for f in findings:
        counts[f.severity] += 1
    if not findings:
        for fl in scan.flags:
            counts[fl.severity] += 1
    out.append("## Severity summary\n")
    out.append("| " + " | ".join(_BADGE[s] for s in Severity) + " |")
    out.append("|" + "---|" * len(Severity))
    out.append("| " + " | ".join(str(counts[s]) for s in Severity) + " |\n")

    if analysis:
        out.append("## Executive summary\n")
        out.append(analysis.executive_summary + "\n")

        out.append("## Findings\n")
        ordered = sorted(findings, key=lambda f: f.severity.rank, reverse=True)
        for i, f in enumerate(ordered, 1):
            flag = "" if f.grounded else "  ⚠️ *(ungrounded — not matched to scan data; review)*"
            out.append(f"### {i}. {f.title} — {_BADGE[f.severity]}{flag}")
            out.append(f"- **Affected:** `{f.affected}`")
            out.append(f"- **Why it matters:** {f.why_it_matters}")
            out.append(f"- **Remediation:** {f.remediation}")
            out.append(f"- **Evidence:** {f.evidence}\n")

        out.append("## Attack narrative\n")
        out.append(analysis.attack_narrative + "\n")
    else:
        out.append("## Rule-based findings (no AI analysis)\n")
        for fl in sorted(scan.flags, key=lambda f: f.severity.rank, reverse=True):
            loc = f"{fl.host}:{fl.port}" if fl.port else fl.host
            out.append(f"- {_BADGE[fl.severity]} **{fl.title}** @ `{loc}` — {fl.detail}")
        out.append("")

    out.append("## Methodology / hosts\n")
    for h in scan.hosts:
        title = f"### {h.address}" + (f" ({h.hostname})" if h.hostname else "")
        out.append(title)
        if h.os_guess:
            out.append(f"- OS guess: {h.os_guess}")
        out.append("| Port | Service | Product / Version |")
        out.append("|------|---------|-------------------|")
        for s in h.services:
            out.append(f"| {s.port}/{s.protocol} | {s.service or '?'} | {s.label or '-'} |")
        out.append("")

    out.append("---")
    out.append(f"*Generated by Recon Reporter on {datetime.now().isoformat(timespec='seconds')}.*")
    return "\n".join(out)
